"""add credits_required and update activity model

Revision ID: ef0389f8f80f
Revises: 7e4ad7f16874
Create Date: 2025-06-20 08:44:34.644841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef0389f8f80f'
down_revision: Union[str, Sequence[str], None] = '7e4ad7f16874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('duration', sa.Integer(), nullable=True))
    op.drop_column('activity', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('activity', 'duration')
    # ### end Alembic commands ###
